# Generated by Django 5.0.7 on 2024-07-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
