# Generated by Django 5.0.6 on 2024-07-27 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=10, null=True)),
                ('avg', models.CharField(blank=True, max_length=10, null=True)),
                ('obp', models.CharField(blank=True, max_length=10, null=True)),
                ('ops', models.CharField(blank=True, max_length=10, null=True)),
                ('rbi', models.IntegerField(blank=True, null=True)),
                ('hits', models.IntegerField(blank=True, null=True)),
                ('runs', models.IntegerField(blank=True, null=True)),
                ('at_bats', models.IntegerField(blank=True, null=True)),
                ('doubles', models.IntegerField(blank=True, null=True)),
                ('triples', models.IntegerField(blank=True, null=True)),
                ('home_runs', models.IntegerField(blank=True, null=True)),
                ('left_on_base', models.IntegerField(blank=True, null=True)),
                ('strike_outs', models.IntegerField(blank=True, null=True)),
                ('base_on_balls', models.IntegerField(blank=True, null=True)),
                ('stolen_bases', models.IntegerField(blank=True, null=True)),
                ('era', models.CharField(blank=True, max_length=10, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('holds', models.IntegerField(blank=True, null=True)),
                ('blown_saves', models.IntegerField(blank=True, null=True)),
                ('earned_runs', models.IntegerField(blank=True, null=True)),
                ('innings_pitched', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_pitches', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='stats.team')),
            ],
        ),
    ]
