# Generated by Django 5.0.6 on 2024-07-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_statleader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statleader',
            name='player_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statleader',
            name='stat_type',
            field=models.CharField(max_length=100),
        ),
    ]
