# Generated by Django 5.0.6 on 2024-07-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_alter_statleader_player_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statleader',
            name='stat_type',
        ),
    ]
